(()=>{
const G=["pop","rock","jazz","classical","electronic","dance","house","techno","hip hop","country","folk","blues","soul","reggae","metal","indie","oldies","80s","news","talk","sports","ambient","chillout","latin","lofi","k-pop"];
const S={favs:"ww.favs",recents:"ww.recents",dead:"ww.dead",vol:"ww.vol",theme:"ww.theme",recs:"ww.recMeta"};
const MAX=3*60*60*1000,BR=48000,PAGE=36;
const el=id=>document.getElementById(id);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={view:"discover",query:"",tag:"",country:"",cc:"",order:"votes",offset:0,stations:[],countries:[],current:null,
dead:new Set(JSON.parse(localStorage.getItem(S.dead)||"[]")),
favs:JSON.parse(localStorage.getItem(S.favs)||"[]"),
recents:JSON.parse(localStorage.getItem(S.recents)||"[]"),
recordings:JSON.parse(localStorage.getItem(S.recs)||"[]"),
recBlobs:new Map(),api:"https://de1.api.radio-browser.info",hideBroken:true,sleep:null};
const audio=el("audio");audio.volume=Number(localStorage.getItem(S.vol)||.85);el("vol").value=audio.volume;
let graph=null,rec=null,chunks=[],t0=0,tick=null,segs=[],on=false;
function toast(m){const t=el("toast");t.hidden=false;t.textContent=m;clearTimeout(toast.i);toast.i=setTimeout(()=>t.hidden=true,3200)}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
async function discover(){for(const b of["https://de1.api.radio-browser.info","https://nl1.api.radio-browser.info","https://at1.api.radio-browser.info"]){try{if((await fetch(b+"/json/stats",{headers:{"User-Agent":"WorldwaveRadio/1.0"}})).ok){state.api=b;return}}catch{}}}
async function api(path,p={}){const u=new URL(state.api+path);Object.entries(p).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")u.searchParams.set(k,v)});const r=await fetch(u,{headers:{"User-Agent":"WorldwaveRadio/1.0",Accept:"application/json"}});if(!r.ok)throw new Error("api");return r.json()}
function dead(s){return!s||state.dead.has(s.stationuuid)||(state.hideBroken&&Number(s.lastcheckok)===0)||!(s.url_resolved||s.url)}
function markDead(s){if(!s?.stationuuid)return;state.dead.add(s.stationuuid);save(S.dead,[...state.dead].slice(-2000));toast((s.name||"Station")+" looks dead — hidden");render(state.stations.filter(x=>!dead(x)))}
function url(s){return s.url_resolved||s.url}
function tags(s){return(s.tags||"").split(",").map(t=>t.trim()).filter(Boolean).slice(0,4)}
function loc(s){return[s.state,s.country].filter(Boolean).join(", ")}
function artF(n){const l=encodeURIComponent((n||"W")[0].toUpperCase());return`data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'><rect fill='%231a1d27' width='64' height='64' rx='14'/><text x='50%' y='56%' text-anchor='middle' fill='%23e8b86d' font-size='28' font-family='Georgia'>${l}</text></svg>`}
function art(s){return s.favicon||artF(s.name)}
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&","<":"<",">":">",'"':""","'":"&#39;"}[c]))}
function graphOn(){if(graph)return graph;const ctx=new(window.AudioContext||window.webkitAudioContext)();const src=ctx.createMediaElementSource(audio);const an=ctx.createAnalyser();an.fftSize=64;const dest=ctx.createMediaStreamDestination();src.connect(an);an.connect(ctx.destination);src.connect(dest);graph={ctx,src,an,dest};viz();return graph}
function viz(){const c=el("viz"),g=c.getContext("2d");(function loop(){requestAnimationFrame(loop);g.clearRect(0,0,c.width,c.height);if(!graph||audio.paused)return;const d=new Uint8Array(graph.an.frequencyBinCount);graph.an.getByteFrequencyData(d);const w=c.width/d.length;d.forEach((v,i)=>{const h=(v/255)*c.height;g.fillStyle=`rgba(232,184,109,${.35+v/400})`;g.fillRect(i*w,c.height-h,w-1,h)})})()}
async function play(st){if(!st)return;state.current=st;now();$$(".card").forEach(c=>c.classList.toggle("playing",c.dataset.uuid===st.stationuuid));audio.crossOrigin="anonymous";const u=url(st);audio.src=u;try{graphOn();if(graph.ctx.state==="suspended")await graph.ctx.resume()}catch{}
try{await audio.play();el("playBtn").textContent="❚❚";api("/json/url/"+st.stationuuid).catch(()=>{});recent(st);if(on)segs.push({name:st.name});ms(st)}
catch{if(audio.crossOrigin){audio.removeAttribute("crossorigin");audio.src=u;try{await audio.play();el("playBtn").textContent="❚❚";recent(st);toast("Playing — capture may be blocked");return}catch{}}markDead(st);el("playBtn").textContent="▶"}}
function stop(){audio.pause();audio.removeAttribute("src");audio.load();el("playBtn").textContent="▶"}
function toggle(){if(!state.current)return surprise();if(audio.paused)audio.play().then(()=>el("playBtn").textContent="❚❚").catch(()=>play(state.current));else{audio.pause();el("playBtn").textContent="▶"}}
function ms(st){if(!("mediaSession"in navigator))return;navigator.mediaSession.metadata=new MediaMetadata({title:st.name,artist:loc(st)||"Worldwave",album:tags(st)[0]||"Radio"});navigator.mediaSession.setActionHandler("play",toggle);navigator.mediaSession.setActionHandler("pause",toggle);navigator.mediaSession.setActionHandler("nexttrack",surprise)}
function isFav(s){return state.favs.some(f=>f.stationuuid===s.stationuuid)}
function slim(s){return{stationuuid:s.stationuuid,name:s.name,url:s.url,url_resolved:s.url_resolved,favicon:s.favicon,tags:s.tags,country:s.country,countrycode:s.countrycode,state:s.state,codec:s.codec,bitrate:s.bitrate,lastcheckok:s.lastcheckok}}
function fav(st){if(!st)return;if(isFav(st)){state.favs=state.favs.filter(f=>f.stationuuid!==st.stationuuid);toast("Removed from favorites")}else{state.favs.unshift(slim(st));state.favs=state.favs.slice(0,400);toast("Saved to favorites")}save(S.favs,state.favs);now();if(state.view==="favorites")showFav();else render(state.stations)}
function recent(st){state.recents=[slim(st),...state.recents.filter(r=>r.stationuuid!==st.stationuuid)].slice(0,80);save(S.recents,state.recents)}
function now(){const s=state.current;el("nowName").textContent=s?s.name:"Nothing playing";el("nowMeta").textContent=s?[loc(s),s.codec,s.bitrate?s.bitrate+" kbps":"",tags(s)[0]].filter(Boolean).join(" · "):"Pick a station to start";el("nowArt").src=s?art(s):artF("W");el("favNowBtn").textContent=s&&isFav(s)?"♥":"♡"}
function card(s){const tg=tags(s).map(t=>`<span class="tag">${esc(t)}</span>`).join("");const pl=state.current&&state.current.stationuuid===s.stationuuid?" playing":"";return`<article class="card${pl}" data-uuid="${s.stationuuid}"><div class="card-top"><img src="${esc(art(s))}" alt="" onerror="this.src='${artF(s.name)}'"/><div><h3>${esc(s.name)}</h3><div class="meta">${esc(loc(s)||"Unknown location")} · ${esc((s.codec||"").toUpperCase())} ${s.bitrate||""}</div></div></div><div class="tags">${tg}</div><div class="card-actions"><button class="play" data-act="play">Play</button><button data-act="fav">${isFav(s)?"♥ Saved":"♡ Save"}</button></div></article>`}
function render(list,append=false){const live=list.filter(s=>!dead(s));state.stations=append?state.stations.concat(live):live;const grid=el("grid");const html=live.map(card).join("");if(append)grid.insertAdjacentHTML("beforeend",html);else grid.innerHTML=html;el("empty").hidden=!!live.length;if(!live.length){el("empty").hidden=false;el("empty").innerHTML="<h3>No working stations in this slice</h3><p>Try another genre, country, or search.</p>"}
el("resultMeta").textContent=state.stations.length+" working station"+(state.stations.length===1?"":"s");
const cards=append?[...grid.querySelectorAll(".card")].slice(-live.length):[...grid.querySelectorAll(".card")];
cards.forEach(c=>{const st=state.stations.find(s=>s.stationuuid===c.dataset.uuid);c.onclick=ev=>{if(ev.target.dataset.act==="fav")fav(st);else play(st)}})}
function setView(v,t,d){state.view=v;$$(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===v));el("pageTitle").textContent=t;el("pageLede").textContent=d;el("chipRow").innerHTML="";el("moreBtn").hidden=true}
async function load(p,append=false){el("resultMeta").textContent="Tuning catalog…";const q={hidebroken:state.hideBroken?"true":"false",limit:PAGE,offset:append?state.offset:0,order:state.order,reverse:state.order==="name"?"false":"true",...p};if(state.order==="random"){q.order="random";delete q.reverse}
try{const rows=await api("/json/stations/search",q);state.offset=(append?state.offset:0)+rows.length;render(rows.filter(s=>!dead(s)),append);el("moreBtn").hidden=rows.length<PAGE;el("moreBtn").onclick=()=>load(p,true)}
catch{await discover();try{const rows=await api("/json/stations/search",q);render(rows.filter(s=>!dead(s)),append)}catch{toast("Could not reach radio-browser.info")}}}
function pills(){el("quickPills").innerHTML=["jazz","classical","news","lofi","metal","country","talk"].map(g=>`<button class="pill" data-tag="${g}">${g}</button>`).join("");$$("#quickPills .pill").forEach(b=>b.onclick=()=>openGenre(b.dataset.tag))}
function showDiscover(){setView("discover","Tune the planet","Highest-voted working stations from the global public catalog.");pills();load({})}
function showGenres(){setView("genres","By genre","Open a lane to hear live stations that last-checked as working.");el("grid").innerHTML=G.map(g=>`<button class="card genre-card" data-tag="${g}"><div class="eyebrow">Genre</div><h3>${g}</h3><div class="count">→</div></button>`).join("");$$(".genre-card").forEach(c=>c.onclick=()=>openGenre(c.dataset.tag));el("resultMeta").textContent=G.length+" genres"}
function openGenre(tag){state.tag=tag;state.country="";state.cc="";setView("discover",tag[0].toUpperCase()+tag.slice(1),`Working stations tagged “${tag}”.`);paint();load({tag})}
async function showPlaces(){setView("places","By location","Every country in the directory. Open one for live streams.");if(!state.countries.length){el("resultMeta").textContent="Loading countries…";state.countries=(await api("/json/countries",{order:"stationcount",reverse:"true"})).filter(c=>c.iso_3166_1&&c.stationcount>0)}
const q=(el("searchInput").value||"").trim().toLowerCase();const rows=state.countries.filter(c=>!q||c.name.toLowerCase().includes(q)||c.iso_3166_1.toLowerCase()===q);
el("grid").innerHTML=rows.map(c=>`<button class="card place-card" data-cc="${c.iso_3166_1}" data-name="${esc(c.name)}"><div class="eyebrow">${c.iso_3166_1}</div><h3>${esc(c.name)}</h3><div class="count">${c.stationcount.toLocaleString()}</div></button>`).join("");
$$(".place-card").forEach(c=>c.onclick=()=>openCountry(c.dataset.cc,c.dataset.name));el("resultMeta").textContent=rows.length+" countries"}
function openCountry(code,name){state.cc=code;state.country=name;state.tag="";setView("discover",name,`Stations from ${name}. Dead links stay out.`);paint();load({countrycode:code})}
function paint(){const box=el("activeFilters");const bits=[];if(state.tag)bits.push(["genre",state.tag]);if(state.country)bits.push(["place",state.country]);if(state.query)bits.push(["search",state.query]);box.hidden=!bits.length;box.innerHTML=bits.map(([k,v])=>`<span class="filter-tag">${k}: ${esc(v)}</span>`).join("")+(bits.length?`<button class="chip" id="clearFilters">Clear</button>`:"");const c=el("clearFilters");if(c)c.onclick=()=>{state.tag=state.country=state.cc=state.query="";el("searchInput").value="";showDiscover()}}
function showFav(){setView("favorites","Favorites","Stored only in this browser.");const live=state.favs.filter(s=>!dead(s));render(live);if(!live.length){el("empty").hidden=false;el("empty").innerHTML="<h3>No favorites yet</h3><p>Heart a station or tap Save on a card.</p>"}}
function showRecent(){setView("recent","Recently played","Your last tuned stations on this device.");render(state.recents.filter(s=>!dead(s)))}
function showLib(){setView("library","Recordings","48 kbps, max 3 hours. Changing stations does not stop a take.");if(!state.recordings.length){el("grid").innerHTML="";el("empty").hidden=false;el("empty").innerHTML="<h3>No takes yet</h3><p>Hit Rec while a station plays. The file downloads when you stop.</p>";el("resultMeta").textContent="0 recordings";return}
el("empty").hidden=true;el("grid").innerHTML=state.recordings.map(r=>`<article class="card" data-id="${r.id}"><h3>${esc(r.title)}</h3><div class="meta">${esc(r.when)} · ${esc(r.duration)} · 48 kbps</div><div class="meta">${esc((r.stations||[]).join(" → "))}</div><div class="card-actions"><button class="play" data-act="dl">Download</button></div></article>`).join("");
el("resultMeta").textContent=state.recordings.length+" recording"+(state.recordings.length===1?"":"s");
$$("#grid .card").forEach(card=>{card.querySelector("[data-act=dl]").onclick=()=>{const r=state.recordings.find(x=>x.id===card.dataset.id);const b=state.recBlobs.get(r.id);if(!b)return toast("This take is gone after reload");dl(b,r.file)}})}
async function surprise(){try{const p={hidebroken:"true",order:"random",limit:12};if(state.tag)p.tag=state.tag;if(state.cc)p.countrycode=state.cc;const rows=(await api("/json/stations/search",p)).filter(s=>!dead(s));if(!rows.length)return toast("No random station in this filter");const pick=rows[Math.floor(Math.random()*rows.length)];toast("Random: "+pick.name);play(pick)}catch{toast("Could not fetch a random station")}}
function mime(){return["audio/webm;codecs=opus","audio/webm","audio/mp4","audio/ogg;codecs=opus"].find(t=>MediaRecorder.isTypeSupported(t))||""}
async function recToggle(){if(on)return recStop();if(!state.current)return toast("Play a station first");if(!window.MediaRecorder)return toast("This browser cannot record");try{graphOn();if(graph.ctx.state==="suspended")await graph.ctx.resume()}catch{return toast("Cannot tap this stream (CORS). Try another station.")}
let stream=graph?.dest?.stream;if(!stream||!stream.getAudioTracks().length){if(audio.captureStream)stream=audio.captureStream();else if(audio.mozCaptureStream)stream=audio.mozCaptureStream()}
if(!stream)return toast("Recording unavailable for this stream");chunks=[];segs=[{name:state.current.name}];try{rec=new MediaRecorder(stream,{mimeType:mime()||undefined,audioBitsPerSecond:BR})}catch{rec=new MediaRecorder(stream)}
rec.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};rec.onstop=finish;rec.start(1000);on=true;t0=Date.now();el("recBtn").classList.add("on");el("recBtn").textContent="■ Stop";tick=setInterval(clock,250);toast("Recording — change stations anytime");setTimeout(()=>{if(on)recStop()},MAX)}
function clock(){const ms=Math.min(Date.now()-t0,MAX);el("recTime").textContent=fmt(ms);if(ms>=MAX&&on)recStop()}
function fmt(ms){const s=Math.floor(ms/1000);return String(Math.floor(s/3600)).padStart(2,"0")+":"+String(Math.floor((s%3600)/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
function recStop(){if(!on||!rec)return;on=false;clearInterval(tick);el("recBtn").classList.remove("on");el("recBtn").textContent="● Rec";try{rec.stop()}catch{}}
function finish(){const blob=new Blob(chunks,{type:rec.mimeType||"audio/webm"});const ext=blob.type.includes("mp4")?"m4a":blob.type.includes("ogg")?"ogg":"webm";const names=[...new Set(segs.map(s=>s.name))];const title=names[0]+(names.length>1?` +${names.length-1}`:"");const id="r"+Date.now();const file=`worldwave-${slug(title)}-${Date.now()}.${ext}`;const row={id,title,file,when:new Date().toLocaleString(),duration:fmt(Date.now()-t0),stations:names};state.recordings.unshift(row);state.recBlobs.set(id,blob);save(S.recs,state.recordings.slice(0,40));dl(blob,file);toast("Saved "+row.duration+" at 48 kbps");if(state.view==="library")showLib()}
function slug(s){return String(s).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,40)||"take"}
function dl(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),4000)}
async function search(q){state.query=q.trim();if(!state.query){if(state.view==="places")return showPlaces();return showDiscover()}
setView("discover","Search",`Results for “${state.query}”.`);paint();const country=state.countries.find(c=>c.name.toLowerCase()===state.query.toLowerCase()||c.iso_3166_1.toLowerCase()===state.query.toLowerCase());const genre=G.find(g=>g===state.query.toLowerCase());if(country)return openCountry(country.iso_3166_1,country.name);if(genre)return openGenre(genre);await load({name:state.query})}
function bind(){$$(".nav-btn").forEach(b=>b.onclick=()=>{const v=b.dataset.view;if(v==="discover"){state.tag=state.country=state.cc=state.query="";el("searchInput").value="";el("activeFilters").hidden=true;showDiscover()}if(v==="genres")showGenres();if(v==="places")showPlaces();if(v==="favorites")showFav();if(v==="recent")showRecent();if(v==="library")showLib();el("sidebar").classList.remove("open")});
el("menuBtn").onclick=()=>el("sidebar").classList.toggle("open");el("randomBtn").onclick=surprise;el("playBtn").onclick=toggle;el("stopBtn").onclick=stop;el("favNowBtn").onclick=()=>fav(state.current);el("recBtn").onclick=recToggle;
el("muteBtn").onclick=()=>{audio.muted=!audio.muted;el("muteBtn").textContent=audio.muted?"🔇":"🔊"};
el("vol").oninput=e=>{audio.volume=+e.target.value;localStorage.setItem(S.vol,audio.volume)};
el("sortSelect").onchange=e=>{state.order=e.target.value;if(state.view==="discover")load({tag:state.tag||undefined,countrycode:state.cc||undefined,name:state.query||undefined})};
el("hideBroken").onchange=e=>{state.hideBroken=e.target.checked;if(state.view==="discover")load({tag:state.tag||undefined,countrycode:state.cc||undefined,name:state.query||undefined})};
el("sleepSelect").onchange=e=>{clearTimeout(state.sleep);const m=+e.target.value;if(!m)return;state.sleep=setTimeout(()=>{stop();if(on)recStop();toast("Sleep timer ended");el("sleepSelect").value="0"},m*60*1000);toast("Sleep in "+m+" min")};
el("themeBtn").onclick=()=>{const n=document.documentElement.getAttribute("data-theme")==="light"?"dark":"light";document.documentElement.setAttribute("data-theme",n==="dark"?"":"light");localStorage.setItem(S.theme,n)};
let t;el("searchInput").addEventListener("input",e=>{clearTimeout(t);t=setTimeout(()=>search(e.target.value),280)});
audio.addEventListener("error",()=>{if(state.current)markDead(state.current)});
document.addEventListener("keydown",e=>{const typing=["INPUT","TEXTAREA","SELECT"].includes(e.target.tagName);if(e.key==="/"&&!typing){e.preventDefault();el("searchInput").focus()}if(typing)return;if(e.key===" "){e.preventDefault();toggle()}if(e.key==="r"||e.key==="R")surprise();if(e.key==="f"||e.key==="F")fav(state.current)})}
async function init(){if(localStorage.getItem(S.theme)==="light")document.documentElement.setAttribute("data-theme","light");bind();pills();now();await discover();try{state.countries=(await api("/json/countries",{order:"stationcount",reverse:"true"})).filter(c=>c.iso_3166_1&&c.stationcount>0)}catch{state.countries=[]}showDiscover()}
init();
})();
